import type { NextPage } from 'next'
import { useState } from 'react';
import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import { Company } from '../types';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aroundhome TimeSlots Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

// export async function getStaticProps() {
//   // console.log(context);
//   const rawdata = axios.get('/api/getData').then(res => res).catch(err => err);
//   const data = JSON.stringify(rawdata);
//   if (!data) {
//     return {
//       notFound: true,
//     }
//   }

//   return {
//     props: data,
//   }
// }

export default Home
